"""Fixtures that load golden master data generated by the R prego package."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

GOLDEN_DIR = Path(__file__).parent


def _load_json(name: str) -> dict:
    """Load a golden master JSON file."""
    path = GOLDEN_DIR / name
    if not path.exists():
        pytest.skip(f"Golden master file not found: {path}")
    with open(path) as f:
        return json.load(f)


def _rows_to_df(rows: list[dict]) -> pd.DataFrame:
    """Convert a list-of-dicts (row-oriented JSON) to a DataFrame."""
    return pd.DataFrame(rows)


def _rows_to_pssm_df(rows: list[dict]) -> pd.DataFrame:
    """Convert row-oriented PSSM JSON to a pyprego-style PSSM DataFrame."""
    df = pd.DataFrame(rows)
    # Ensure column order: pos, A, C, G, T
    cols = ["pos", "A", "C", "G", "T"]
    for c in cols:
        if c not in df.columns:
            if c == "pos":
                df["pos"] = range(len(df))
    return df[cols].reset_index(drop=True)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def golden_example_data() -> dict:
    """Load the example data subset (sequences, response_mat, etc.)."""
    return _load_json("example_data.json")


@pytest.fixture(scope="session")
def golden_compute_pwm() -> dict:
    """Load compute_pwm golden master data."""
    return _load_json("compute_pwm.json")


@pytest.fixture(scope="session")
def golden_screen_kmers() -> dict:
    """Load screen_kmers golden master data."""
    return _load_json("screen_kmers.json")


@pytest.fixture(scope="session")
def golden_generate_kmers() -> dict:
    """Load generate_kmers golden master data."""
    return _load_json("generate_kmers.json")


@pytest.fixture(scope="session")
def golden_kmer_matrix() -> dict:
    """Load kmer_matrix golden master data."""
    return _load_json("kmer_matrix.json")


@pytest.fixture(scope="session")
def golden_pssm_cor() -> dict:
    """Load pssm_cor golden master data."""
    return _load_json("pssm_cor.json")


@pytest.fixture(scope="session")
def golden_pssm_trim() -> dict:
    """Load pssm_trim golden master data."""
    return _load_json("pssm_trim.json")


@pytest.fixture(scope="session")
def golden_bits_per_pos() -> dict:
    """Load bits_per_pos golden master data."""
    return _load_json("bits_per_pos.json")


@pytest.fixture(scope="session")
def golden_consensus() -> dict:
    """Load consensus_from_pssm golden master data."""
    return _load_json("consensus_from_pssm.json")


@pytest.fixture(scope="session")
def golden_rc() -> dict:
    """Load rc golden master data."""
    return _load_json("rc.json")


@pytest.fixture(scope="session")
def golden_dinucs() -> dict:
    """Load calc_sequences_dinucs golden master data."""
    return _load_json("calc_sequences_dinucs.json")


@pytest.fixture(scope="session")
def golden_pssm_theoretical() -> dict:
    """Load pssm_theoretical golden master data."""
    return _load_json("pssm_theoretical.json")


@pytest.fixture(scope="session")
def golden_pssm_rc() -> dict:
    """Load pssm_rc golden master data."""
    return _load_json("pssm_rc.json")


@pytest.fixture(scope="session")
def golden_pssm_diff() -> dict:
    """Load pssm_diff golden master data."""
    return _load_json("pssm_diff.json")


@pytest.fixture(scope="session")
def golden_freq_local_pwm() -> dict:
    """Load calc_freq_local_pwm golden master data."""
    return _load_json("calc_freq_local_pwm.json")
